### ISSUE TITLE
https://test.cstar.pagopa.it/bpd/hb/citizens/DMMMLN76R58C514Q] - timeout - ambiente UAT

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#186]
Salve, 

potreste verificare? 

[DEBUG] [25/03/2021 19.18.07 771] [pool-4-thread-353] [SCA - SESSIONID [77145EB95D37E181BEDF84F116EF7501.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [emanuelaannamaria.dimmito] - CASHBACK - WSCall - START BonusPagamentiDigitaliService - enrollmentCitizenStatus ]
[INFO] [25/03/2021 19.18.07 771] [pool-4-thread-353] [SCA - SESSIONID [77145EB95D37E181BEDF84F116EF7501.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [emanuelaannamaria.dimmito] - CASHBACK - WSCall - BonusPagamentiDigitaliService - enrollmentCitizenStatus - HTTP URL
[https://test.cstar.pagopa.it/bpd/hb/citizens/DMMMLN76R58C514Q]]
[INFO] [25/03/2021 19.18.07 771] [pool-4-thread-353] [SCA - SESSIONID [77145EB95D37E181BEDF84F116EF7501.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [emanuelaannamaria.dimmito] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET
- REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: d382258f-d037-47b4-8a32-4f2da4b023de]]
[INFO] [25/03/2021 19.18.07 772] [pool-4-thread-353] [SCA - SESSIONID [77145EB95D37E181BEDF84F116EF7501.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [emanuelaannamaria.dimmito] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET
- REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/citizens/DMMMLN76R58C514Q]
[ERROR] [25/03/2021 19.18.13 094] [pool-4-thread-353] [SCA - SESSIONID [77145EB95D37E181BEDF84F116EF7501.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [emanuelaannamaria.dimmito] - CASHBACK - WSCall - BonusPagamentiDigitaliService - Exception] [java.net.SocketTimeout
Exception: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:171)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
at sun.security.ssl.InputRecord.read(InputRecord.java:503)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:84)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)

**Comment by daniloMessinaSia** [comment]
Buongiorno,
sono in corso verifiche lato rete,
vi aggiorneremo appena avremo riscontro

**Comment by daniloMessinaSia** [comment]
Buongiorno,
potreste riprovare e darci riscontro?

Grazie

**Comment by NicolaLamberti** [comment]
anomalia rientrata
