### ISSUE TITLE
https://test.cstar.pagopa.it/bpd/hb/citizens/FLVNDR89B27F839K]

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#187]
Salve, 

riceviamo il seguente errore

[DEBUG] [26/03/2021 09.39.30 243] [pool-4-thread-311] [SCA - SESSIONID [33536C8B5A6BE97E602B11E3D9729FCF.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [andrea.flavia] - CASHBACK - WSCall - START BonusPagamentiDigitaliService - enrollmentCitizenStatus ]
[INFO] [26/03/2021 09.39.30 243] [pool-4-thread-311] [SCA - SESSIONID [33536C8B5A6BE97E602B11E3D9729FCF.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [andrea.flavia] - CASHBACK - WSCall - BonusPagamentiDigitaliService - enrollmentCitizenStatus - HTTP URL[https://tes
t.cstar.pagopa.it/bpd/hb/citizens/FLVNDR89B27F839K]]
[INFO] [26/03/2021 09.39.30 243] [pool-4-thread-311] [SCA - SESSIONID [33536C8B5A6BE97E602B11E3D9729FCF.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [andrea.flavia] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET - REQUEST H
EADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: c3c034e0-6152-448a-ae5f-c3de670b7425]]
[INFO] [26/03/2021 09.39.30 243] [pool-4-thread-311] [SCA - SESSIONID [33536C8B5A6BE97E602B11E3D9729FCF.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [andrea.flavia] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET - REQUEST P
AYLOAD - https://test.cstar.pagopa.it/bpd/hb/citizens/FLVNDR89B27F839K]
[ERROR] [26/03/2021 09.39.35 532] [pool-4-thread-311] [SCA - SESSIONID [33536C8B5A6BE97E602B11E3D9729FCF.mobile] - COMMAND SCA [Async - v1/postepay/statoUtenteCashba
ck] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [andrea.flavia] - CASHBACK - WSCall - BonusPagamentiDigitaliService - Exception] [java.net.SocketTimeoutException: R
ead timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:171)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
at sun.security.ssl.InputRecord.read(InputRecord.java:503)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:84)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)

**Comment by daniloMessinaSia** [comment]
Buongiorno,
sono in corso verifiche lato rete,
vi aggiorneremo appena avremo riscontro

**Comment by daniloMessinaSia** [comment]
Buongiorno,
potreste riprovare e darci riscontro?

Grazie

**Comment by NicolaLamberti** [comment]
anomalia rientrata
